config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);
  
Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
	
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index', 'home']);

    $routes->connect('/post-travel-packages/package-list', ['controller' => 'PostTravlePackages', 'action' => 'packageList']);
    $routes->connect('/post-travel-packages/view/*', ['controller' => 'PostTravlePackages', 'action' => 'view']);

    $routes->connect('/home', ['controller' => 'Pages', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    //$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'index']);
    //$routes->connect('/pages/package', ['controller' => 'Pages', 'action' => 'package']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

src/Model/Table/UsersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \App\Model\Table\CountriesTable|\Cake\ORM\Association\BelongsTo $Countries
 * @property \App\Model\Table\CitiesTable|\Cake\ORM\Association\BelongsTo $Cities
 * @property \App\Model\Table\StatesTable|\Cake\ORM\Association\BelongsTo $States
 * @property \App\Model\Table\RolesTable|\Cake\ORM\Association\BelongsTo $Roles
 * @property \App\Model\Table\DevicesTable|\Cake\ORM\Association\BelongsTo $Devices
 * @property \App\Model\Table\BusinessBuddiesTable|\Cake\ORM\Association\HasMany $BusinessBuddies
 * @property \App\Model\Table\CreditsTable|\Cake\ORM\Association\HasMany $Credits
 * @property \App\Model\Table\EventPlannerPromotionCartsTable|\Cake\ORM\Association\HasMany $EventPlannerPromotionCarts
 * @property \App\Model\Table\EventPlannerPromotionLikesTable|\Cake\ORM\Association\HasMany $EventPlannerPromotionLikes
 * @property \App\Model\Table\EventPlannerPromotionReportsTable|\Cake\ORM\Association\HasMany $EventPlannerPromotionReports
 * @property \App\Model\Table\EventPlannerPromotionViewsTable|\Cake\ORM\Association\HasMany $EventPlannerPromotionViews
 * @property \App\Model\Table\EventPlannerPromotionsTable|\Cake\ORM\Association\HasMany $EventPlannerPromotions
 * @property \App\Model\Table\HotelPromotionCartsTable|\Cake\ORM\Association\HasMany $HotelPromotionCarts
 * @property \App\Model\Table\HotelPromotionLikesTable|\Cake\ORM\Association\HasMany $HotelPromotionLikes
 * @property \App\Model\Table\HotelPromotionReportsTable|\Cake\ORM\Association\HasMany $HotelPromotionReports
 * @property \App\Model\Table\HotelPromotionViewsTable|\Cake\ORM\Association\HasMany $HotelPromotionViews
 * @property \App\Model\Table\HotelPromotionsTable|\Cake\ORM\Association\HasMany $HotelPromotions
 * @property \App\Model\Table\HotelsTable|\Cake\ORM\Association\HasMany $Hotels
 * @property \App\Model\Table\PostTravlePackageCartsTable|\Cake\ORM\Association\HasMany $PostTravlePackageCarts
 * @property \App\Model\Table\PostTravlePackageLikesTable|\Cake\ORM\Association\HasMany $PostTravlePackageLikes
 * @property \App\Model\Table\PostTravlePackageReportsTable|\Cake\ORM\Association\HasMany $PostTravlePackageReports
 * @property \App\Model\Table\PostTravlePackageViewsTable|\Cake\ORM\Association\HasMany $PostTravlePackageViews
 * @property \App\Model\Table\PostTravlePackagesTable|\Cake\ORM\Association\HasMany $PostTravlePackages
 * @property \App\Model\Table\PromotionTable|\Cake\ORM\Association\HasMany $Promotion
 * @property \App\Model\Table\RequestsTable|\Cake\ORM\Association\HasMany $Requests
 * @property \App\Model\Table\ResponsesTable|\Cake\ORM\Association\HasMany $Responses
 * @property \App\Model\Table\TaxiFleetPromotionCartsTable|\Cake\ORM\Association\HasMany $TaxiFleetPromotionCarts
 * @property \App\Model\Table\TaxiFleetPromotionLikesTable|\Cake\ORM\Association\HasMany $TaxiFleetPromotionLikes
 * @property \App\Model\Table\TaxiFleetPromotionReportsTable|\Cake\ORM\Association\HasMany $TaxiFleetPromotionReports
 * @property \App\Model\Table\TaxiFleetPromotionViewsTable|\Cake\ORM\Association\HasMany $TaxiFleetPromotionViews
 * @property \App\Model\Table\TaxiFleetPromotionsTable|\Cake\ORM\Association\HasMany $TaxiFleetPromotions
 * @property \App\Model\Table\TempRatingsTable|\Cake\ORM\Association\HasMany $TempRatings
 * @property \App\Model\Table\TestimonialTable|\Cake\ORM\Association\HasMany $Testimonial
 * @property \App\Model\Table\TransportsTable|\Cake\ORM\Association\HasMany $Transports
 * @property \App\Model\Table\TravelCertificatesTable|\Cake\ORM\Association\HasMany $TravelCertificates
 * @property \App\Model\Table\UserChatsTable|\Cake\ORM\Association\HasMany $UserChats
 * @property \App\Model\Table\UserFeedbacksTable|\Cake\ORM\Association\HasMany $UserFeedbacks
 * @property \App\Model\Table\UserRatingsTable|\Cake\ORM\Association\HasMany $UserRatings
 * @property \App\Model\Table\UserRightsTable|\Cake\ORM\Association\HasMany $UserRights
 * @property \App\Model\Table\UserdetailsTable|\Cake\ORM\Association\HasMany $Userdetails
 *
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, callable $callback = null, $options = [])
 */
class UsersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('users');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Countries', [
            'foreignKey' => 'country_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Cities', [
            'foreignKey' => 'city_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('States', [
            'foreignKey' => 'state_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Roles', [
            'foreignKey' => 'role_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Devices', [
            'foreignKey' => 'device_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('BusinessBuddies', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Credits', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('EventPlannerPromotionCarts', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('EventPlannerPromotionLikes', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('EventPlannerPromotionReports', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('EventPlannerPromotionViews', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('EventPlannerPromotions', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('HotelPromotionCarts', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('HotelPromotionLikes', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('HotelPromotionReports', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('HotelPromotionViews', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('HotelPromotions', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Hotels', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('PostTravlePackageCarts', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('PostTravlePackageLikes', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('PostTravlePackageReports', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('PostTravlePackageViews', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('PostTravlePackages', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Promotion', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Requests', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Responses', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TaxiFleetPromotionCarts', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TaxiFleetPromotionLikes', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TaxiFleetPromotionReports', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TaxiFleetPromotionViews', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TaxiFleetPromotions', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TempRatings', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Testimonial', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Transports', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TravelCertificates', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('UserChats', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('UserFeedbacks', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('UserRatings', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('UserRights', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Userdetails', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('TripitoesRatings', [
            'foreignKey' => 'user_id'
        ]);

        $this->belongsTo('HotelState', [
            'className' => 'States',
            'foreignKey' => 'state_id',
            'propertyName' => 'hotel_state'
        ]);
        $this->belongsTo('PCountries', [
            'className' => 'Countries',
            'foreignKey' => 'country_id',
            'propertyName' => 'p_country'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')

src/Template/Element/blogs.ctp
<?php
if(sizeof($tripitoesBlogs->toArray())>0){  
    foreach ($tripitoesBlogs as $key => $blog) {
    ?>
      <li class="animate fadeInUp" data-wow-delay="0.4s">
        <div class="row"> 
          <!--  Image -->
          <div class="col-sm-5"> 
            <?= $this->Html->image($cdn_path.$blog->image_url,['alt'=>'','class'=>'redirect img-responsive','width'=>'336px','height'=>'214px','redirectid'=>$this->Url->build(['controller'=>'Pages','action'=>'blogDetails/'.$blog->id])]);?>
          </div>
          <div class="col-sm-7"> 
            <?= $this->Html->link($blog->title, ['controller'=>'Pages','action'=>'blogDetails',$blog->id], ['escape'=>false,'class'=>'tittle-post']) ?>
            <ul class="info">
              <li><i class="fa fa-user"></i> Written by - <span style="text-transform: capitalize;color: #5f9a02;">Preeti Singh</span></li>
            </ul>
            <p>
              <?= $this->Text->truncate($blog->short_description, 100, ['ellipsis' => '...','exact' => true]); ?> 
            </p>
            <!--  Post Info -->
            <ul class="info"> 
              <li><i class="fa fa-calendar-o"></i> <?= $blog->created_on->format('d-M');?></li>
              <li><i class="fa fa-comment"></i> <?= $blog->total_comment;?></li>
               <?php  $shareLink = $this->Url->build(['controller'=>'Pages','action'=>'blogList','_full'=>true,'_ssl'=>true]); ?> 
              <li style="float: right;"><i class="fa fa-share"></i> Share on -  
                <a href="javascript:void(0);" class="shareBtn" shareLink="<?= $shareLink ?>"><i style=" padding: 8px 10px;  background: #000; color: #fff;   margin-right: 5px;" class="fa fa-facebook"></i></a>
                <a href="https://plus.google.com/share?url=<?= $shareLink; ?>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" ><i style="padding: 8px 5.7px; background: #000; color: #fff;" class="fa fa-google-plus"></i></a>


              </li>
            </ul>
            <?= $this->Html->link('READ MORE', ['controller'=>'Pages','action'=>'blogDetails',$blog->id], ['escape'=>false,'class'=>'btn btn-small btn-dark']) ?>
          </div>
        </div>
      </li>
      
    <?php
    }
}
?>

src/Template/Element/blogs_old.ctp
<?php
if(sizeof($tripitoesBlogs->toArray())>0){  
    foreach ($tripitoesBlogs as $key => $blog) {
    ?>
      <li class="animate fadeInUp" data-wow-delay="0.4s">
        <div class="row"> 
          <!--  Image -->
          <div class="col-sm-5"> 
            <?= $this->Html->image($cdn_path.$blog->image_url,['alt'=>'','class'=>'redirect img-responsive','width'=>'336px','height'=>'214px','redirectid'=>$this->Url->build(['controller'=>'Pages','action'=>'blogDetails/'.$blog->id])]);?>
          </div>
          <div class="col-sm-7"> 
            <?= $this->Html->link($blog->title, ['controller'=>'Pages','action'=>'blogDetails',$blog->id], ['escape'=>false,'class'=>'tittle-post']) ?>
            <ul class="info">
              <li><i class="fa fa-user"></i> Written by - <span style="text-transform: capitalize;color: #5f9a02;">Preeti Singh</span></li>
            </ul>
            <p>
              <?= $this->Text->truncate($blog->short_description, 100, ['ellipsis' => '...','exact' => true]); ?> 
            </p>
            <!--  Post Info -->
            <ul class="info"> 
              <li><i class="fa fa-calendar-o"></i> <?= $blog->created_on->format('d-M');?></li>
              <li><i class="fa fa-comment"></i> <?= $blog->total_comment;?></li>
               <?php  $shareLink = $this->Url->build(['controller'=>'Pages','action'=>'blogList','_full'=>true,'_ssl'=>true]); ?> 
              <li style="float: right;"><i class="fa fa-share"></i> Share on -  
                <a href="javascript:void(0);" class="shareBtn" shareLink="<?= $shareLink ?>"><i style=" padding: 8px 10px;  background: #000; color: #fff;   margin-right: 5px;" class="fa fa-facebook"></i></a>
                <a href="https://plus.google.com/share?url=<?= $shareLink; ?>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" ><i style="padding: 8px 5.7px; background: #000; color: #fff;" class="fa fa-google-plus"></i></a>


              </li>
            </ul>
            <?= $this->Html->link('READ MORE', ['controller'=>'Pages','action'=>'blogDetails',$blog->id], ['escape'=>false,'class'=>'btn btn-small btn-dark']) ?>
          </div>
        </div>
      </li>
      
    <?php
    }
}
?>

src/Template/Element/div_loader.ctp
 <style type="text/css">
  .div-content{left: 0; top: 0; right: 0; bottom: 0;}
  .overlay-divloader {
      position: absolute;
      transform: translateY(-50%);
       -webkit-transform: translateY(-50%);
       -ms-transform: translateY(-50%);
      top: 50%;
      left: 0;
      right: 0;
      text-align: center;
      color: #555;
      background-color: rgba(255,255,255,0.8);
      height: 100%;
      z-index: 2;
  }
</style>
<div id="beforeload" style="display: none">
	<div class="overlay-divloader">
		<div class="loading" style="top: 35%;width: 150px;text-indent: 0;font-size: 12px;">
			<p class="text-left" style="margin-left: 11px;"><i>Please Wait...</i></p>
			<div class="ball"></div>
			<div class="ball"></div>
			<div class="ball"></div>
		</div>
	</div>
</div>

src/Template/Element/hotel.ctp
<?php
foreach ($hotelPromotions as $hotelPromotion) 
{
  $ratingData=$TripitoesRating->rating($hotelPromotion);
  $total_users=$ratingData['total_users'];
  $overallrating=$ratingData['overallrating'];
   if($total_users==0){
        $total_users=1;
        $overallrating=5;
    }
	$url = (strtolower($hotelPromotion->hotel_name));
	$urlTitle=str_replace(" ","-",$url);
	$urlTitle=str_replace("/","-",$urlTitle);
  ?>
  <div class="items-in">
    <div class="row">
      <div class="col-sm-4 col-md-12 col-lg-5"> 
        <!-- Image -->
        <div class="img redirect" redirectid="<?= $this->Url->build(['controller'=>'HotelPromotions','action'=>'details/'.$hotelPromotion->id.'/'.$urlTitle]) ?>">
          <?= $this->Html->image('hello.png',['alt'=>'Tripitoes','class'=>'spaical lazy','data-src'=>$cdn_path.$hotelPromotion->hotel_pic]);?>
        </div>
      </div>
      <div class="col-sm-8 col-md-12 col-lg-7">
        <div class="details-sec"> 
            <?= $this->Html->link(ucwords(strtolower($hotelPromotion->hotel_name)),['controller'=>'HotelPromotions','action'=>'details/'.$hotelPromotion->id.'/'.$urlTitle],['class'=>'title','data-toggle'=>'tooltip','title'=>ucwords(strtolower($hotelPromotion->hotel_name))]) ?>
        </div>
        <p class="h_category font-montserrat responseive" style="display:none"> 
          City: <span color="#A7A7A7"><?= $hotelPromotion->city->name.'('.$hotelPromotion->city->state->state_name.')'; ?></span>
        </p>
        <div class="stars">
            <?php 
              for($x=1;$x<=5 ;){
                 
                  if($hotelPromotion->hotel_rating>=$x)  {
                    echo'<i class="fa fa-star"></i>';
                  }
                  else{
                    echo'<i class="fa fa-star-o"></i>';
                  }
                   $x++;
              }
               ?>
            <span style="color:#39aeff; font-size:14px;"><?= $hotelPromotion->hotel_rating ?> Star</span>
        </div>
        <?php
          if($hotelPromotion->user->isVerified==1)
          {?>
              <div class="verified dasktopverify">
                <?= $this->Html->image('hello.png',['class'=>'img-responsive lazy','alt'=>'','data-src'=>$cdn_path.'tripitoes_images/verified.png']);?>
              </div>
              <span class="verified mobileverify" style="display:none">
                  <?= $this->Html->image('hello',['style'=>'height: 25px !important; width: 26px !important;','alt'=>'Tripitoes','class'=>'lazy','data-src'=>$cdn_path.'tripitoes_images/verifiedmobile.png']);?>
              </span>
          <?php
          }
          ?>
        
        <p class="font-montserrat h_category" data-toggle="tooltip" title="<?= $hotelPromotion->hotel_category->name ?>">Category: 
          <span>
            <?= $hotelPromotion->hotel_category->name; ?>
          </span>
        </p> 
        <div class="seller_rating">
          <div class="seller-icon">
            <i class="fa fa-star"></i>
          </div>
          <div class="s-rate">
            <span style="color:#39aeff; font-size:12px;"><?= $overallrating ?></span><span style="color:#000; font-size:10px;">/5</span>
            <span style="color:#000; font-size:8px; letter-spacing: 1px; line-height: 10px;">(<?= $total_users ?>)</span>
          </div>
          <div class="s-text">
            <span>Seller Rating</span>
          </div>
        </div>
        
        <p class="h_location font-montserrat hotelData"> 
          City: <span color="#A7A7A7"><?= $hotelPromotion->city->name.'('.$hotelPromotion->city->state->state_name.')'; ?></span>
        </p>
        <p class="price font-montserrat">Starting Price: <span>Rs. <?= $hotelPromotion->trip_price ?></span></p>
        <div class="full-width item-btn-com"> 
          <a href="<?= $this->Url->build(['controller'=>'HotelPromotions','action'=>'details/'.$hotelPromotion->id,$urlTitle]) ?>" ><i class="ion ion-ios-eye-outline"></i><span><?= $hotelPromotion->trip_views ?></span></a>
         
          <?php
          if($auth_login=='Yes')
          {
            echo $this->Html->link('<i class="ion ion-ios-heart-outline"></i><span>'.$hotelPromotion->trip_total_like.'</span>',['controller'=>'HotelPromotions','action'=>'hotelLike',$hotelPromotion->id,$tripitoes_user_id],['escape'=>false,'class'=>'hotelLike']);
          }
          else
          {
            echo $this->Html->link('<i class="ion ion-ios-heart-outline"></i><span>'.$hotelPromotion->trip_total_like.'</span>','#pop-open',['escape'=>false,'class'=>'link popup-vedio video-btn']);
          }
          ?>
          <a href="tel:<?= $hotelPromotion->user->mobile_number; ?>" class="CallCount" redirecturl="<?= $this->Url->build(['controller'=>'HotelPromotions','action'=>'saveCall/'.$hotelPromotion->id]) ?>"><i class="ion ion-ios-telephone-outline"  data-original-title="<?= $hotelPromotion->user->mobile_number; ?>" data-toggle="tooltips"></i><span>Call</span></a>
        </div>
        <?php 
        if(!empty($hotelPromotion->booknowlink)){
    			$website=$hotelPromotion->booknowlink; 
    			$website=str_replace("http://","",$website);
    			$website=str_replace("https://","",$website);
          echo '<a href="http://'.$website.'" class="btn-small btn-dark" rel="noreferrer" target="_blank">BOOK NOW</a>';
        }
        ?>
      </div>
    </div>
  </div>
  <?php
}
?>

src/Template/Element/sell_popup.ctp
<div id="sell-Popup" class="zoom-anim-dialog mfp-hide pop-open-style">
  <div class="pop_up">
    <div class="video"> 
        <h6>Sell your Travel Packages, Hotels, or Taxi Services here by joining TravelB2BHub.com!  </h6>
        <div align="left" style="width:100%;margin-top:0px">
        <p>It is also an all India B2B Tourism Network / Marketplace!</p>

        <?php echo $this->Html->link('Take me There <i class="fa fa-arrow-circle-right"></i>','https://travelb2bhub.com/',
             ['escape'=>false,'class'=>'apply-btn','style'=>'color:#FFF;font-size:12px !important','target'=>'_blank','rel'=>"noreferrer"]
        ); ?>

        
        <?php echo $this->Html->link('Download App <i class="fa fa-arrow-circle-right"></i>','https://play.google.com/store/apps/details?id=com.app.travel.TravelB2B',
             ['escape'=>false,'class'=>'apply-btn','style'=>'color:#FFF;font-size:12px !important','target'=>'_blank','rel'=>"noreferrer"]
        ); ?>
        </div>                     
    </div>
  </div>
</div>